name: ede_final_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.6.2
  flutter_bloc: ^8.1.3
  sqflite: ^2.4.1
  http: ^1.2.2
  path: ^1.9.0
  postgres: ^3.4.7
  crypto: ^3.0.6
  flutter_secure_storage: ^9.2.2
  dart_jsonwebtoken: ^2.14.2
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  path_provider: ^2.1.1
  app_settings: ^5.1.1
  google_maps_flutter: ^2.10.0
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  equatable: ^2.0.7
  flutter_speed_dial: ^7.0.0
  dio: ^5.7.0
  shared_preferences: ^2.3.5
  connectivity_plus: ^6.1.1
  retry: ^3.1.2
  flutter_svg: ^2.0.9
  pdf: ^3.10.7
  csv: ^5.1.1
  intl: ^0.19.0
  share_plus: ^7.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/icons/svg/
